### ISSUE TITLE
overwriteable MELTANO_CLI_LOG_CONFIG environment variable

### ISSUE THREAD

**Issue by resulyrt93** [quantile-development/dagster-meltano#34]
We want to pass a new logging configuration file path to meltano resource through environment variable with that command `export MELTANO_CLI_LOG_CONFIG=/<my-path>/logging.conf`, not via run configuration. But when i try this, it doesn't pass to meltano environment since in package `MELTANO_CLI_LOG_CONFIG` envvar is overwritten. I think [here](https://github.com/quantile-development/dagster-meltano/blob/master/dagster_meltano/meltano_resource.py#L39) should be like following to allow it.
```python
return {
        "MELTANO_CLI_LOG_CONFIG": str(Path(__file__).parent / "logging.yaml"),
        "DBT_USE_COLORS": "false",
        "NO_COLOR": "1",
        **os.environ.copy()
}
```

Is there any reason to overwrite that i can't notice?

**Comment by JulesHuisman** [comment]
No that is totally fine! 

The idea behind it was to give users the option to have a `MELTANO_CLI_LOG_CONFIG` when they run meltano using the cli, and then overwrite this in the package. But I think that is quite a rare occurrence, your use case is probably more applicable.

If you make a PR I can deploy the changes.

**Comment by resulyrt93** [comment]
Thanks, I created a PR for it. It's waiting your approve. Also i can't attach my PR to this issue. Can you do that?
