### ISSUE TITLE
Should you be able to import dagster jobs as ops?

### ISSUE THREAD

**Issue by ReneTC** [quantile-development/dagster-meltano#36]
Beginner here,
But to me many of the meltano jobs are actually an operation instead.

This would allow you to make a nice meltano: extract op, transform op and load op.
Then join them together nicely in the UI as a job in dagster

**Comment by ReneTC** [comment]
Closing as you can chain with by using `meltano_command_op`

example from readme:
```
from dagster import repository, job
from dagster_meltano import meltano_resource, meltano_run_op

@job(resource_defs={"meltano": meltano_resource})
def meltano_run_job():
    tap_done = meltano_run_op("tap-1 target-1")()
    meltano_run_op("tap-2 target-2")(tap_done)

@repository()
def repository():
    return [meltano_run_job]
```

**Comment by JulesHuisman** [comment]
You are also able to use multiple tasks. Or doesn't that work for your usecase?

```yaml
jobs:
- name: fetch_raw_data
  tasks:
  - utils:raw_data
  - another:task
```

**Comment by ReneTC** [comment]
it works brilliantly. Well done.
